// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjvwdtgkkwpvspdgnzgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdndkdGdra3dwdnNwZGduemdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NDg1MzksImV4cCI6MjA1MjMyNDUzOX0.JxughZQmPVV6oOFou-QhfI4yS9Zxl1ryBZ4q-NVjUHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);